#!/bin/bash -e

BUILD_PATH=build/

function build {
    # configure
    mkdir -p $BUILD_PATH && cmake -B $BUILD_PATH .

    # build
    cmake --build $BUILD_PATH
}

# build if forced or if executable doesn't exist
if [[ ! -f $BUILD_PATH/cekeh-client ]] || [[ "$1" == "-f" ]] || [[ "$1" == "--force" ]]; then
    build
fi

printf "\n---\n\n"

# run
$BUILD_PATH/cekeh-client