#!/bin/bash -e

# cekeh-client run
# Created: 2021-12-29
# Author : ThomasvanBommel
#
# Modificaitons:
# 2021-12-29 - Added support for cmake

BUILD_PATH=build/

# build if forced or if executable doesn't exist
if [[ ! -f $BUILD_PATH/cekeh-client ]] || [[ "$1" == "-f" ]] || [[ "$1" == "--force" ]]; then
    # configure
    mkdir -p $BUILD_PATH && cmake -B $BUILD_PATH .

    # build
    cmake --build $BUILD_PATH
fi

# space application output from the build output
printf "\n---\n\n"

# run
$BUILD_PATH/cekeh-client